language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install --upgrade pytest coveralls pytest-cov
  - pip install matplotlib pandas weasyprint==51
  - pip install -e .
# command to run tests
script:
  - python -m pytest -v --cov flametree --cov-report term-missing

after_success:
  - coveralls
